name: Issue Comment Posted

on:
  issue_comment:
    types: [edited]

jobs:
  check-pr-labels:
    runs-on: ubuntu-20.04

    steps:
      - name: Create app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PR_APP_ID }}
          private-key: ${{ secrets.PR_APP_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          sparse-checkout: build_tools

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install PyGithub
        run: pip install -Uq PyGithub

      - name: Assign issue
        id: assign
        run: python build_tools/comment_pr_labeler.py
        env:
          CONTEXT_GITHUB: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - if: ${{ steps.assign.outputs.empty_commit}}
        name: Push empty commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Empty commit for CI
          commit_user_name: aeon-actions-bot[bot]
          commit_options: "--allow-empty"
