name: Monthly GitHub maintenance

on:
  schedule:
    # every 1st of the month at 12:30 AM UTC
    - cron:  "30 0 1 * *"
  workflow_dispatch:

jobs:

  stale_branches:
    runs-on: ubuntu-24.04

    steps:
      - name: Create app token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.PR_APP_ID }}
          private-key: ${{ secrets.PR_APP_KEY }}

      - name: Stale Branches
        uses: crs-k/stale-branches@v8.2.2
        with:
          repo-token: ${{ steps.app-token.outputs.token }}
          days-before-stale: 365
          days-before-delete: 455
          comment-updates: true
          compare-branches: "info"
          pr-check: true
