name: PR typecheck

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "aeon/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    # run the code coverage job if a PR has the '' label
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run typecheck test') }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install aeon, dependencies and mypy
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: python -m pip install .[all_extras,unstable_extras,dev] mypy

      - name: Show dependencies
        run: python -m pip list

      - name: Run mypy typecheck
        run: mypy aeon/
