name: Update pre-commit Hooks

on:
  schedule:
    # every Monday at 12:30 AM UTC
    - cron:  "30 0 * * 1"

jobs:
  pre-commit-auto-update:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - uses: browniebroke/pre-commit-autoupdate-action@v1.0.0

      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Automated `pre-commit` hook update"
          branch: pre-commit-hooks-update
          title: "[MNT] Automated `pre-commit` hook update"
          body: "Automated weekly update to `.pre-commit-config.yaml` hook versions."
          labels: maintenance, no changelog
