name: Update Contributors

on:
  push:
    branches:
      - main
    paths:
      - '.all-contributorsrc'

jobs:
  generate-markdown-and-commit:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup all-contributors-cli
        run: npm install -g all-contributors-cli

      - name: Generate CONTRIBUTORS.md
        id: generate
        run: npx all-contributors generate

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PR_APP_ID }}
          private-key: ${{ secrets.PR_APP_KEY }}

      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "Automated `CONTRIBUTORS.md` update"
          branch: update_contributors
          title: "[MNT] Automated `CONTRIBUTORS.md` update"
          body: "Automated update to CONTRIBUTORS.md caused by an update to the `.all-contributorsrc` file."
          labels: maintenance, no changelog
